"""
CONTRACT MENU
"""
BASE_FOR_CONTRACT_MENU = 'CONTRACT_MENU_'

ABOUT_CONTRACT_MENU = BASE_FOR_CONTRACT_MENU + 'ABOUT_CONTRACT_MENU'
MY_FINES_MENU = BASE_FOR_CONTRACT_MENU + 'MY_FINES_MENU'

REMOVE_KEYBOARD = BASE_FOR_CONTRACT_MENU + 'RMV_KBRD'
TO_MAIN_MENU = BASE_FOR_CONTRACT_MENU + 'TO_MAIN_MENU'

GET_PHOTOS_CAR_CONTRACT = 'SEND_PHOTOS_CAR_CONTRACT'

GET_INFO_ABOUT_MY_CAR = BASE_FOR_CONTRACT_MENU + 'GET_INFO_ABOUT_MY_CAR'

"""
CONTRACT COMMANDS
"""
BASE_FOR_CONTRACT_COMMANDS = 'CONTRACT_COMMANDS_'

# For work with personal data
BASE_FOR_ACCEPT_PD = BASE_FOR_CONTRACT_COMMANDS + 'PD_'
PD_IS_CORRECT = BASE_FOR_ACCEPT_PD + 'IS_CORRECT'
PD_IS_WRONG = BASE_FOR_ACCEPT_PD + 'PD_WRONG'

# For work with contract medias
BASE_FOR_DOWNLOAD_CONTRACT = BASE_FOR_CONTRACT_COMMANDS + 'DOWNLOAD_'
DOWNLOAD_CONTRACT_FILE = BASE_FOR_DOWNLOAD_CONTRACT + 'FILE'
DOWNLOAD_CONTRACT_PHOTOS = BASE_FOR_DOWNLOAD_CONTRACT + 'PHOTO_CAR'

# For work with user's fines
BASE_FOR_FINES_COMMANDS = BASE_FOR_CONTRACT_COMMANDS + 'FINES_'
MY_ALL_FINES = BASE_FOR_FINES_COMMANDS + 'MY_ALL_FINES'
MY_PAID_FINES = BASE_FOR_FINES_COMMANDS + 'MY_PAID_FINES'
MY_UNPAID_FINES = BASE_FOR_FINES_COMMANDS + 'MY_UNPAID_FINES'
