BASE_FOR_CONTRACT_MENU = 'CONTRACT_MENU_'
REMOVE_KEYBOARD = BASE_FOR_CONTRACT_MENU + 'RMV_KBRD'

BASE_FOR_DOWNLOAD_CONTRACT = 'DOWNLOAD_CONTRACT_'
DOWNLOAD_CONTRACT_FILE = BASE_FOR_DOWNLOAD_CONTRACT + 'FILE'
DOWNLOAD_CONTRACT_PHOTOS = BASE_FOR_DOWNLOAD_CONTRACT + 'PHOTO_CAR'

SEND_PHOTOS_CAR_CONTRACT = 'SEND_PHOTOS_CAR_CONTRACT'

BASE_FOR_ACCEPT = 'PD_'
CORRECT = 'PD_CORRECT'
WRONG = 'PD_WRONG'
