# Generated by Django 3.2.7 on 2021-10-07 11:16

from django.db import migrations, models
import django.db.models.deletion
import rentcars.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tgbot', '0002_delete_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='personal_data', serialize=False, to='tgbot.user')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=100, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('gender', models.IntegerField(choices=[(0, 'male'), (1, 'female')], verbose_name='Пол')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('email', models.EmailField(help_text='Почтааааа', max_length=70, verbose_name='Почта')),
                ('phone_number', models.CharField(max_length=12, validators=[rentcars.validators.phone_number_validator])),
                ('passport_serial', models.CharField(max_length=4, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(max_length=6, verbose_name='Номер паспорта')),
                ('passport_date_of_issue', models.DateField(verbose_name='Дата выдачи паспорта')),
                ('passport_issued_by', models.CharField(max_length=255, verbose_name='Кем выдан паспорт')),
                ('address_registration', models.CharField(max_length=256, verbose_name='Адрес прописки')),
                ('address_of_residence', models.CharField(max_length=256, verbose_name='Адрес места жительства')),
                ('close_person_name', models.CharField(max_length=50, verbose_name='Близкий человек')),
                ('close_person_phone', models.CharField(max_length=12, validators=[rentcars.validators.phone_number_validator])),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
