# Generated by Django 3.2.7 on 2021-10-07 15:28

import django.core.validators
from django.db import migrations, models
import rentcars.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rentcars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personaldata',
            options={'verbose_name': 'Персональные данные', 'verbose_name_plural': 'Персональные данные'},
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='address_of_residence',
            field=models.CharField(max_length=256, validators=[rentcars.validators.address_validator], verbose_name='Адрес места жительства'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='address_registration',
            field=models.CharField(max_length=256, validators=[rentcars.validators.address_validator], verbose_name='Адрес прописки'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='birthday',
            field=models.DateField(validators=[rentcars.validators.birthday_date_validate], verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='close_person_name',
            field=models.CharField(max_length=50, validators=[rentcars.validators.close_person_name_validator], verbose_name='Близкий человек'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='close_person_phone',
            field=models.CharField(max_length=12, validators=[rentcars.validators.phone_number_validator], verbose_name='Номер близкого человека'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='email',
            field=models.EmailField(max_length=70, validators=[django.core.validators.EmailValidator(message='Адрес электронной почты должен быть правильным. Например, rustamwho@mail.com')], verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='first_name',
            field=models.CharField(max_length=100, validators=[rentcars.validators.russian_letters_validator], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Мужской'), (1, 'Женский')], verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='last_name',
            field=models.CharField(max_length=100, validators=[rentcars.validators.russian_letters_validator], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='middle_name',
            field=models.CharField(max_length=100, validators=[rentcars.validators.russian_letters_validator], verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='passport_issued_by',
            field=models.CharField(max_length=255, validators=[rentcars.validators.passport_issued_by_validator], verbose_name='Кем выдан паспорт'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='passport_number',
            field=models.CharField(max_length=6, validators=[rentcars.validators.passport_number_validator], verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='passport_serial',
            field=models.CharField(max_length=4, validators=[rentcars.validators.passport_serial_validator], verbose_name='Серия паспорта'),
        ),
    ]
