# Generated by Django 3.2.9 on 2021-11-23 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentcars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(help_text='Выберите из списка владельца авто', on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='rentcars.personaldata', verbose_name='Владелец авто'),
        ),
    ]
