# Generated by Django 3.2.7 on 2021-10-08 13:13

from django.db import migrations, models
import rentcars.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rentcars', '0002_auto_20211007_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='close_person_address',
            field=models.CharField(default='г. Казань ул. 2-я Привольная, д. 33А', max_length=256, validators=[rentcars.validators.address_validator], verbose_name='Адрес места жительства'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='gender',
            field=models.IntegerField(choices=[(0, 'М'), (1, 'Ж')], verbose_name='Пол'),
        ),
    ]
