# Generated by Django 3.2.7 on 2021-10-08 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_delete_location'),
        ('rentcars', '0003_auto_20211008_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='contracts/', verbose_name='Файл договора')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата формирования договора')),
                ('closed_at', models.DateField(verbose_name='Дата завершения действия договора')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contact', to='tgbot.user')),
            ],
        ),
    ]
