# Generated by Django 3.2.7 on 2021-10-09 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_delete_location'),
        ('rentcars', '0004_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='tgbot.user'),
        ),
    ]
