# Generated by Django 3.2.7 on 2021-10-16 12:08

from django.db import migrations, models
import rentcars.models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcars', '0005_alter_contract_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Договор', 'verbose_name_plural': 'Договоры'},
        ),
        migrations.AddField(
            model_name='contract',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Подтвержден'),
        ),
        migrations.AddField(
            model_name='contract',
            name='photo_car',
            field=models.ImageField(blank=True, upload_to=rentcars.models.contract_photos_path, verbose_name='Фотографии машины'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='file',
            field=models.FileField(upload_to='contracts/files/', verbose_name='Файл договора'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Муж'), (1, 'Жен')], verbose_name='Пол'),
        ),
    ]
