# Generated by Django 3.2.7 on 2021-10-16 12:32

from django.db import migrations, models
import django.db.models.deletion
import rentcars.models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcars', '0006_auto_20211016_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='photo_car',
        ),
        migrations.CreateModel(
            name='PhotoCarContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=rentcars.models.contract_photos_path, verbose_name='Фотографии машины')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_photos', to='rentcars.contract')),
            ],
        ),
    ]
