# Generated by Django 3.2.7 on 2021-10-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcars', '0007_auto_20211016_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photocarcontract',
            options={'verbose_name': 'Фотография машины во время заключения договора', 'verbose_name_plural': 'Фотографии машины во время заключения договора'},
        ),
        migrations.AddField(
            model_name='photocarcontract',
            name='file_id',
            field=models.CharField(blank=True, max_length=250, verbose_name='ID фотографии на серверах Telegram'),
        ),
    ]
