# Generated by Django 3.2.7 on 2021-10-23 19:35

from django.db import migrations, models
import django.db.models.deletion
import rentcars.models
import rentcars.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rentcars', '0008_auto_20211017_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=9, validators=[rentcars.validators.license_plate_validator], verbose_name='Регистрационный знак')),
                ('vin', models.CharField(max_length=17, validators=[rentcars.validators.vin_validator], verbose_name='VIN')),
                ('model', models.CharField(max_length=50, verbose_name='Марка, модель')),
                ('type', models.CharField(max_length=50, verbose_name='Тип ТС')),
                ('category', models.CharField(help_text='Одна английская буква из ABCD', max_length=1, validators=[rentcars.validators.vehicle_category_validator], verbose_name='Категория ТС')),
                ('year_manufacture', models.IntegerField(validators=[rentcars.validators.vehicle_manufactured_year_validator], verbose_name='Год выпуска')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет ТС')),
                ('power', models.IntegerField(verbose_name='Мощность двигателя, л.с.')),
                ('ecological_class', models.CharField(max_length=20, verbose_name='Экологический класс')),
                ('vehicle_passport_serial', models.CharField(max_length=4, validators=[rentcars.validators.vehicle_passport_serial_validator], verbose_name='Серия ПТС')),
                ('vehicle_passport_number', models.CharField(max_length=6, validators=[rentcars.validators.passport_number_validator], verbose_name='Номер ПТС')),
                ('max_mass', models.IntegerField(verbose_name='Разрешенная max масса, кг')),
                ('sts_serial', models.CharField(max_length=4, validators=[rentcars.validators.sts_serial_validator], verbose_name='Серия свидетельства о регистрации ТС')),
                ('sts_number', models.CharField(max_length=6, validators=[rentcars.validators.sts_number_validator], verbose_name='Номер свидетельства о регистрации ТС')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='PhotoCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=rentcars.models.contract_photos_path, verbose_name='Фотографии машины')),
                ('file_id', models.CharField(blank=True, max_length=250, verbose_name='ID фотографии на серверах Telegram')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rentcars.car')),
            ],
            options={
                'verbose_name': 'Фотография машины',
                'verbose_name_plural': 'Фотографии машины',
            },
        ),
    ]
