# Generated by Django 3.2.7 on 2021-10-23 19:41

from django.db import migrations, models
import rentcars.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rentcars', '0009_car_photocar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year_manufacture',
            field=models.CharField(max_length=4, validators=[rentcars.validators.vehicle_manufactured_year_validator], verbose_name='Год выпуска'),
        ),
    ]
