# Generated by Django 3.2.7 on 2021-10-23 20:04

from django.db import migrations, models
import django.db.models.deletion
import rentcars.models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcars', '0010_alter_car_year_manufacture'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='car', to='rentcars.car'),
        ),
        migrations.AlterField(
            model_name='photocar',
            name='image',
            field=models.ImageField(upload_to=rentcars.models.car_photos_path, verbose_name='Фотографии машины'),
        ),
    ]
