# Generated by Django 3.2.7 on 2021-11-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcars', '0012_auto_20211101_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Штраф оплачен'),
        ),
    ]
