# Generated by Django 3.2.7 on 2021-11-02 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_delete_location'),
        ('rentcars', '0014_contract_approved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='contract',
            field=models.ForeignKey(blank=True, help_text='Заполнится автоматически после сохранения!', null=True, on_delete=django.db.models.deletion.CASCADE, to='rentcars.contract', verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='fine',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Заполнится автоматически после сохранения!', null=True, on_delete=django.db.models.deletion.CASCADE, to='tgbot.user', verbose_name='Водитель'),
        ),
    ]
