BASE_FOR_MENU = 'MENU_EDIT_'

BACK = 'MENU_EDIT_BCK'
REMOVE_KEYBOARD = 'MENU_EDIT_RMV_KBRD'

MENU_EDIT_PD_MAIN = 'MENU_EDIT_PD_MAIN'
MENU_EDIT_PD_PD = 'MENU_EDIT_PD_PD'
MENU_EDIT_CONTACTS = 'MENU_EDIT_CNTCTS'
MENU_EDIT_PASSPORT = 'MENU_EDIT_PSSPRT'
MENU_EDIT_CLOSE_PERSON = 'MENU_EDIT_CLS_PRSN'

BASE_FOR_EDITING = 'EDIT_PD_'

# For personal data "Личные данные" (After EDIT_PD_PD)
EDIT_PD_FIRST_NAME = 'EDIT_PD_FRST_NM'
EDIT_PD_LAST_NAME = 'EDIT_PD_LST_NM'
EDIT_PD_MIDDLE_NAME = 'EDIT_PD_MDDL_NM'
EDIT_PD_GENDER = 'EDIT_PD_GNDR'
EDIT_PD_BIRTHDAY = 'EDIT_PD_BRTHD'

# For personal data "Контакты" (After MENU_EDIT_CONTACTS)
EDIT_PD_EMAIL = 'EDIT_PD_EMAIL'
EDIT_PD_PHONE_NUMBER = 'EDIT_PD_PHONE_NUMBER'
EDIT_PD_ADDRESS_REGISTRATION = 'EDIT_PD_ADDRESS_REGISTRATION'
EDIT_PD_ADDRESS_RESIDENCE = 'EDIT_PD_ADDRESS_RESIDENCE'

# For personal data "Паспорт" (After MENU_EDIT_PASSPORT)
EDIT_PD_PASSPORT_SERIAL = 'EDIT_PD_PASSPORT_SERIAL'
EDIT_PD_PASSPORT_NUMBER = 'EDIT_PD_PASSPORT_NUMBER'
EDIT_PD_PASSPORT_ISSUED_BY = 'EDIT_PD_PASSPORT_ISSUED_BY'
EDIT_PD_PASSPORT_ISSUED_AT = 'EDIT_PD_PASSPORT_ISSUED_AT'

# Строки для близкого человека
