PERSONAL_DATA = ('Ваши данные:\n'
                 '<b>{last_name} {first_name} {middle_name}</b>\n'
                 '<b>Пол:</b> {gender}\n'
                 '<b>Дата рождения:</b> {birthday}\n'
                 '<b>Почта:</b> {email}\n'
                 '<b>Номер телефона:</b> {phone_number}\n'
                 '<b>Паспорт:</b> {passport_serial} №{passport_number}\n'
                 '<b>Выдан:</b> {passport_date_of_issue} '
                 '{passport_issued_by}\n'
                 '<b>Адрес прописки:</b> {address_registration}\n'
                 '<b>Адрес проживания:</b> {address_of_residence}\n\n'
                 '<b>Близкий человек:</b> {close_person_phone} '
                 '{close_person_name}\n'
                 '<b>Адрес:</b> {close_person_address}')
