BASE_ADMIN_MENU = 'MENU_ADMIN_'

BACK = BASE_ADMIN_MENU + 'BCK'
REMOVE_KEYBOARD = BASE_ADMIN_MENU + 'RMV_KBRD'

BASE_ADMIN_COMMANDS = 'ADMIN_CMD_'

GET_ALL_USERS = BASE_ADMIN_COMMANDS + 'GET_ALL_USERS'
GET_ARENDATORS = BASE_ADMIN_COMMANDS + 'GET_ARENDATORS'
