BASE_ADMIN_MENU = 'MENU_ADMIN_'

BACK = BASE_ADMIN_MENU + 'BCK'
REMOVE_KEYBOARD = BASE_ADMIN_MENU + 'RMV_KBRD'
DELETE_MESSAGE = BASE_ADMIN_MENU + 'DEL_MESSAGE'
CARS_MENU = BASE_ADMIN_MENU + 'CARS_MENU'
SET_CAR_TO_CONTRACT_MENU = BASE_ADMIN_MENU + 'SET_CAR_TO_CONTRACT_MENU_'

BASE_ADMIN_COMMANDS = 'ADMIN_CMD_'

GET_ALL_USERS = BASE_ADMIN_COMMANDS + 'GET_ALL_USERS'
GET_ARENDATORS = BASE_ADMIN_COMMANDS + 'GET_ARENDATORS'

GET_UNAPPROVED_CONTRACTS = BASE_ADMIN_COMMANDS + 'GET_UNAPPROVED_CONTRACTS'

BASE_FOR_APPROVE_CONTRACT = BASE_ADMIN_COMMANDS + 'APPROVE_'
BASE_FOR_SET_CAR_TO_CONTRACT = BASE_ADMIN_COMMANDS + 'SET_CAR_'

GET_ALL_CARS = BASE_ADMIN_COMMANDS + 'GET_ALL_CARS'
GET_RENTED_CARS = BASE_ADMIN_COMMANDS + 'GET_RENTED_CARS'
